"""add hamster lat lng

Revision ID: b8948e98deac
Revises: a1c4e7b09f12
Create Date: 2026-04-28 07:01:35.799367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8948e98deac'
down_revision: Union[str, None] = 'a1c4e7b09f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hamsters', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hamsters', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hamsters', 'longitude')
    op.drop_column('hamsters', 'latitude')
    # ### end Alembic commands ###
